version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
#    depends_on:
#      - nginx
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
  nginx:
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    volumes:
      - ./config:/config/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django
